/*
 * Wire
 * Copyright (C) 2016 Wire Swiss GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 *
 */

'use strict';

const CBOR = require('wire-webapp-cbor');
const TypeUtil = require('../util/TypeUtil');

const DerivedSecrets = require('../derived/DerivedSecrets');
const MacKey = require('../derived/MacKey');
const MessageKeys = require('./MessageKeys');

/** @module session */

/**
 * @class ChainKey
 */
class ChainKey {
  /**
   * @param {!derived.MacKey} key - Mac Key generated by derived secrets
   * @param {!number} counter
   * @returns {ChainKey}
   */
  static from_mac_key(key, counter) {
    TypeUtil.assert_is_instance(MacKey, key);
    TypeUtil.assert_is_integer(counter);

    const ck = new ChainKey();
    ck.key = key;
    ck.idx = counter;
    return ck;
  }

  /** @returns {ChainKey} */
  next() {
    const ck = new ChainKey();
    ck.key = new MacKey(this._key.sign('1'));
    ck.idx = this._idx + 1;
    return ck;
  }

  /** @returns {session.MessageKeys} */
  message_keys() {
    const base = this._key.sign('0');
    const dsecs = DerivedSecrets.kdf_without_salt(base, 'hash_ratchet');
    return new MessageKeys(dsecs.cipher_key, dsecs.mac_key, this._idx);
  }

  /**
   * @param {!CBOR.Encoder} e
   * @returns {CBOR.Encoder}
   */
  encode(e) {
    e.object(2);
    e.u8(0);
    this._key.encode(e);
    e.u8(1);
    return e.u32(this._idx);
  }

  /**
   * @param {!CBOR.Decoder} d
   * @returns {ChainKey}
   */
  static decode(d) {
    TypeUtil.assert_is_instance(CBOR.Decoder, d);

    const self = new ChainKey();

    const nprops = d.object();
    for (let i = 0; i <= nprops - 1; i++) {
      switch (d.u8()) {
        case 0:
          self.key = MacKey.decode(d);
          break;
        case 1:
          self.idx = d.u32();
          break;
        default:
          d.skip();
      }
    }

    TypeUtil.assert_is_instance(MacKey, self.key);
    TypeUtil.assert_is_integer(self.idx);

    return self;
  }
}

module.exports = ChainKey;
